-- Databricks notebook source
TRUNCATE TABLE psas_di_qat.340b_gold.T_ACCOUNTCONFIRMATION_LOOKUP_01;
INSERT INTO psas_di_qat.340b_gold.T_ACCOUNTCONFIRMATION_LOOKUP_01
SELECT DISTINCT T_APEXUSFILE.SHIP_TO_ACCT_NO, T_APEXUSFILE.ENTITY_NAME, T_APEXUSFILE.SHIP_TO_ACCT_NAME, T_APEXUSFILE.APEXUS_340B_ID, T_PHS_AUDIT.CUST_ACCT_ID, T_PHS_AUDIT.CUST_ACCT_NAME, T_PHS_AUDIT.STATUS
FROM psas_di_qat.`340b_slvr`.t_apexusfile AS T_APEXUSFILE LEFT JOIN psas_di_qat.`340b_gold`.T_PHS_AUDIT_2 AS T_PHS_AUDIT ON T_APEXUSFILE.SHIP_TO_ACCT_NO = T_PHS_AUDIT.CUST_ACCT_ID
WHERE T_APEXUSFILE.SHIP_TO_ACCT_NO IS NOT NULL
ORDER BY T_PHS_AUDIT.CUST_ACCT_ID;

CREATE OR REPLACE VIEW psas_di_qat.340b_gold.V_ACCOUNTCONFIRMATION_LOOKUP_01 AS SELECT * FROM psas_di_qat.340b_gold.T_ACCOUNTCONFIRMATION_LOOKUP_01;
