-- Databricks notebook source

TRUNCATE TABLE psas_di_qat.340b_gold.T_BUSTYPE_01;
INSERT INTO psas_di_qat.340b_gold.T_BUSTYPE_01
SELECT T_PHS_AUDIT.CUST_ACCT_ID, T_PHS_AUDIT.CUST_ACCT_NAME, T_PHS_AUDIT.ACCT_CLASSIFICATION, T_PHS_AUDIT.UPDATE_SAP, T_PHS_AUDIT.PHS_340B_ID, T_PHS_AUDIT.DEA_NUM, T_PHS_AUDIT.DELIVERY_DOC, T_PHS_AUDIT.BUS_TYP_CD, T_PHS_AUDIT.PVP_PARTICIPATION_FLAG AS PVP_Flag, T_PHS_AUDIT.CUST_CHN_ID, T_PHS_AUDIT.NATIONAL_SUBGRP_CD, T_PHS_AUDIT.COMMENTS, T_PHS_AUDIT.SALES_LSTMTH, T_PHS_AUDIT.SALES_CURMTH
FROM psas_di_qat.340b_slvr.T_PHS_AUDIT AS T_PHS_AUDIT
WHERE (T_PHS_AUDIT.ACCT_CLASSIFICATION in ('004','005') AND T_PHS_AUDIT.BUS_TYP_CD Not In ('31','44') AND T_PHS_AUDIT.CUST_CHN_ID<>'989' AND (case when CHARINDEX('/',CUST_ACCT_NAME) > 0 then 'Y'else 'N' end)='Y' AND UPPER(T_PHS_AUDIT.STATUS)='ACTIVE') OR (T_PHS_AUDIT.ACCT_CLASSIFICATION in ('004','005') AND T_PHS_AUDIT.BUS_TYP_CD='44' AND T_PHS_AUDIT.CUST_CHN_ID<>'989' AND (case when CHARINDEX('/',CUST_ACCT_NAME) > 0 then 'Y'else 'N' end)='N' AND UPPER(T_PHS_AUDIT.STATUS)='ACTIVE' ) OR (T_PHS_AUDIT.ACCT_CLASSIFICATION ='003' AND T_PHS_AUDIT.BUS_TYP_CD Not In ('31','44') AND T_PHS_AUDIT.CUST_CHN_ID<>'989' AND (case when CHARINDEX('/',CUST_ACCT_NAME) > 0 then 'Y'else 'N' end)='Y' AND UPPER(T_PHS_AUDIT.STATUS) ='ACTIVE' ) OR (T_PHS_AUDIT.ACCT_CLASSIFICATION ='003' AND T_PHS_AUDIT.BUS_TYP_CD ='44' AND T_PHS_AUDIT.CUST_CHN_ID<>'989' AND 
(case when CHARINDEX('/',CUST_ACCT_NAME) > 0 then 'Y'else 'N' end)='N' AND UPPER(T_PHS_AUDIT.STATUS) ='ACTIVE')
ORDER BY T_PHS_AUDIT.UPDATE_SAP DESC;

-- COMMAND ----------

CREATE OR REPLACE VIEW psas_di_qat.340b_gold.V_BUSTYPE_01 AS SELECT * FROM psas_di_qat.340b_gold.T_BUSTYPE_01;
