-- Databricks notebook source

UPDATE psas_di_qat.340b_slvr.T_LUTL_PVP_CODING AS LUPVCOD SET  LUPVCOD.Coding = concat( LUPVCOD.Chain , LUPVCOD.SUB_GROUP),  LUPVCOD.PVP_CODING = 'Y'
WHERE ((( LUPVCOD.Coding) Is Null Or ( LUPVCOD.Coding)=''));

-- COMMAND ----------

MERGE INTO psas_di_qat.340b_gold.T_PHS_AUDIT_2 AS PHAUD
USING psas_di_qat.340b_slvr.T_LUTL_PVP_CODING AS LUPVCOD
ON PHAUD.PVP_CODE = LUPVCOD.Coding
WHEN MATCHED AND PHAUD.PVP_CODING <> 'Y' AND LUPVCOD.PVP_CODING = 'Y' AND PHAUD.NATIONAL_GRP_CD <> '0100'
THEN UPDATE SET PHAUD.PVP_CODING = 'Y';

-- COMMAND ----------


--DROP VIEW IF EXISTS psas_di_qat.340b_gold.V_PVP_CODING_AUDIT;
TRUNCATE table psas_di_qat.340b_gold.T_PVP_CODING_AUDIT;
INSERT INTO psas_di_qat.340b_gold.T_PVP_CODING_AUDIT 
SELECT PHAUD.CUST_ACCT_ID, PHAUD.CUST_ACCT_NAME, PHAUD.ZX_BLOCK, PHAUD.PHS_340B_ID, IFF(PHAUD.PVP_PARTICIPATION_FLAG='Y','Y','N') AS PVP_Flag, PHAUD.PVP_CODE, PHAUD.PVP_CODING AS PVP_Coding, PHAUD.CUST_CHN_ID, PHAUD.NATIONAL_SUBGRP_CD, PHAUD.CHAIN_NAM, PHAUD.NATIONAL_SUBGRP_NAME, PHAUD.NATIONAL_GRP_NAME, PHAUD.PVP_EXPIRATION_DATE, PHAUD.HRSA_START_DATE AS HRSA_Start, PHAUD.COMMENTS, PHAUD.PVP_ELIGIBILITY_DATE AS PVP_Start, PHAUD.HRSA_TERM_DATE
FROM psas_di_qat.340b_gold.T_PHS_AUDIT_2 AS PHAUD 
WHERE (((PHAUD.PHS_340B_ID) IS NOT NULL) AND (IFF(PVP_PARTICIPATION_FLAG='Y','Y','N') != PVP_CODING) AND (PHAUD.CUST_CHN_ID != '989') AND (PHAUD.ACCT_CLASSIFICATION in ('004','005')) AND (UPPER(PHAUD.STATUS)='ACTIVE'))
ORDER BY PHAUD.PVP_ELIGIBILITY_DATE;

CREATE OR REPLACE view psas_di_qat.340b_gold.V_PVP_CODING_AUDIT AS SELECT * FROM psas_di_qat.340b_gold.T_PVP_CODING_AUDIT;


-- COMMAND ----------


---01 Q_Activated_PHSWAC
--DROP VIEW IF EXISTS psas_di_qat.340b_gold.T_ACTIVATED_PHSWAC_01;
TRUNCATE table psas_di_qat.340b_gold.T_ACTIVATED_PHSWAC_01;
INSERT INTO psas_di_qat.340b_gold.T_ACTIVATED_PHSWAC_01 
SELECT PHAUD.CUST_ACCT_ID, PHAUD.CUST_ACCT_NAME, PHAUD.ACCT_CLASSIFICATION AS Acct_Class, PHAUD.STATUS, PHAUD.UPDATE_SAP, PHAUD.OPENED_FOR_RETURNS, PHAUD.UPDATE_ACTIVESTATUS AS Active_Status_Update, PHAUD.SALES_CURMTH, PHAUD.SALES_LSTMTH, PHAUD.COMMENTS
FROM psas_di_qat.340b_gold.T_PHS_AUDIT_2 AS PHAUD 
WHERE ((PHAUD.ACCT_CLASSIFICATION='003' OR PHAUD.ACCT_CLASSIFICATION in ('004','005')) AND (UPPER(PHAUD.STATUS)='ACTIVE') AND (PHAUD.UPDATE_ACTIVESTATUS Is Not Null) AND PHAUD.CUST_CHN_ID !='989')
ORDER BY PHAUD.UPDATE_ACTIVESTATUS DESC;

CREATE OR REPLACE VIEW psas_di_qat.340b_gold.V_ACTIVATED_PHSWAC_01 AS SELECT * FROM psas_di_qat.340b_gold.T_ACTIVATED_PHSWAC_01;

-- COMMAND ----------

---02 Q_340B_Exceptions
--DROP VIEW IF EXISTS psas_di_qat.340b_gold.T_340B_EXCEPTIONS_02;
TRUNCATE table psas_di_qat.340b_gold.T_340B_EXCEPTIONS_02;
INSERT INTO psas_di_qat.340b_gold.T_340B_EXCEPTIONS_02 
SELECT PHAUD.CUST_ACCT_ID, PHAUD.CUST_ACCT_NAME, PHAUD.PHS_340B_ID, PHAUD.UPDATE_340BID, PHAUD.COMMENTS
FROM psas_di_qat.340b_gold.T_PHS_AUDIT_2 AS PHAUD LEFT JOIN psas_di_qat.`340b_brnz`.T_OPACE_DAILY_PUBLIC AS OPACE_DAILY_PUBLIC ON PHAUD.PHS_340B_ID = OPACE_DAILY_PUBLIC.340B_ID
WHERE ((PHAUD.PHS_340B_ID Is Not Null) AND (PHAUD.UPDATE_340BID Is Not Null) AND (OPACE_DAILY_PUBLIC.340B_ID Is Null) AND ((PHAUD.CUST_CHN_ID)!='989') AND (UPPER(PHAUD.STATUS)='ACTIVE'))
ORDER BY PHAUD.UPDATE_340BID DESC;

-- COMMAND ----------

-- creating views from Maitee
create or replace view psas_di_qat.340b_gold.V_PVP_CODING_AUDIT as (select * from psas_di_qat.340b_gold.T_PVP_CODING_AUDIT);

-- COMMAND ----------

create or replace view psas_di_qat.340b_gold.V_ACTIVATED_PHSWAC_01 as (select * from psas_di_qat.340b_gold.T_ACTIVATED_PHSWAC_01);

-- COMMAND ----------

create or replace view psas_di_qat.340b_gold.V_LUTL_PVP_CODING as (select * from psas_di_qat.340b_SLVR.T_LUTL_PVP_CODING);
